version: "2.0"

services:
  webgrabplus:
    image: linuxserver/webgrabplus
    expose:
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=6782491fa1ca24463457032df5a8daeb
      - TZ=Etc/UTC

profiles:
  compute:
    webgrabplus:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        webgrabplus:
          denom: uakt
          amount: 100000
deployment:
  webgrabplus:
    akash:
      profile: webgrabplus
      count: 1
