version: "2.0"

services:
  resilio-sync:
    image: linuxserver/resilio-sync
    expose:
      - port: 8888
        as: 8888
        to:
          - global: true
      - port: 55555
        as: 55555
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=75245eda14bc1dade82b78638a82a1c9
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC

profiles:
  compute:
    resilio-sync:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        resilio-sync:
          denom: uakt
          amount: 100000
deployment:
  resilio-sync:
    akash:
      profile: resilio-sync
      count: 1
