version: "2.0"

services:
  libreoffice:
    image: linuxserver/libreoffice
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 3001
        as: 3001
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=8873dc6a0a49e2b41f48f2d7edeaac32
      - TZ=Etc/UTC

profiles:
  compute:
    libreoffice:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        libreoffice:
          denom: uakt
          amount: 100000
deployment:
  libreoffice:
    akash:
      profile: libreoffice
      count: 1
