version: "2.0"

services:
  openvscode-server:
    image: linuxserver/openvscode-server
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - CONNECTION_SECRET=
      - CONNECTION_TOKEN=
      - PASSWORD=4efb1f112b93f0c994e4d1ba88e69240
      - SUDO_PASSWORD_HASH=
      - SUDO_PASSWORD=password
      - TZ=Etc/UTC

profiles:
  compute:
    openvscode-server:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        openvscode-server:
          denom: uakt
          amount: 100000
deployment:
  openvscode-server:
    akash:
      profile: openvscode-server
      count: 1
