version: "2.0"

services:
  pydio:
    image: linuxserver/pydio
    expose:
      - port: 443
        as: 443
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=7716d27a677243333bcab83a4fdeb4c8
      - TZ=Europe/London

profiles:
  compute:
    pydio:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        pydio:
          denom: uakt
          amount: 100000
deployment:
  pydio:
    akash:
      profile: pydio
      count: 1
