version: "2.0"

services:
  htpcmanager:
    image: linuxserver/htpcmanager
    expose:
      - port: 8085
        as: 8085
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=8d9a472bb9867061c38b4a8839254ebf
      - TZ=Etc/UTC

profiles:
  compute:
    htpcmanager:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        htpcmanager:
          denom: uakt
          amount: 100000
deployment:
  htpcmanager:
    akash:
      profile: htpcmanager
      count: 1
