version: "2.0"

services:
  airsonic-advanced:
    image: linuxserver/airsonic-advanced
    expose:
      - port: 4040
        as: 4040
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - CONTEXT_PATH=
      - PASSWORD=ff06ff28e92b975c5b6745d3ff088422
      - JAVA_OPTS=
      - JAVA_OPTS="-Xmx256m
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC

profiles:
  compute:
    airsonic-advanced:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        airsonic-advanced:
          denom: uakt
          amount: 100000
deployment:
  airsonic-advanced:
    akash:
      profile: airsonic-advanced
      count: 1
