version: "2.0"

services:
  overseerr:
    image: linuxserver/overseerr
    expose:
      - port: 5055
        as: 5055
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=93fe894b2efb65200b046ce0702152d7
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC

profiles:
  compute:
    overseerr:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        overseerr:
          denom: uakt
          amount: 100000
deployment:
  overseerr:
    akash:
      profile: overseerr
      count: 1
