version: "2.0"

services:
  {APP_NAME}:
    image: linuxserver/{DOCKER_IMAGE}
    expose:
{PORTS}
    env:
{ENVIRONMENT_VARIABLES}
profiles:
  compute:
    {APP_NAME}:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        {APP_NAME}:
          denom: uakt
          amount: 100000
deployment:
  {APP_NAME}:
    akash:
      profile: {APP_NAME}
      count: 1
