version: "2.0"

services:
  xbackbone:
    image: linuxserver/xbackbone
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 443
        as: 443
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=5a50e6a9e53a3d35bed7a4cdb14380fd
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC

profiles:
  compute:
    xbackbone:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        xbackbone:
          denom: uakt
          amount: 100000
deployment:
  xbackbone:
    akash:
      profile: xbackbone
      count: 1
