version: "2.0"

services:
  diskover:
    image: linuxserver/diskover
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - ES_HOST=elasticsearch
      - ES_PASS=changeme
      - ES_PORT=9200
      - ES_USER=elastic
      - PASSWORD=a9ed5c09f06001ba959a9a0a62f295e4
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC

profiles:
  compute:
    diskover:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        diskover:
          denom: uakt
          amount: 100000
deployment:
  diskover:
    akash:
      profile: diskover
      count: 1
