version: "2.0"

services:
  sickbeard:
    image: linuxserver/sickbeard
    expose:
      - port: 8081
        as: 8081
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - TZ=TZ
      - TZ=<timezone>

profiles:
  compute:
    sickbeard:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        sickbeard:
          denom: uakt
          amount: 100000
deployment:
  sickbeard:
    akash:
      profile: sickbeard
      count: 1
