version: "2.0"

services:
  pyload:
    image: linuxserver/pyload
    expose:
      - port: 8000
        as: 8000
        to:
          - global: true
      - port: 7227
        as: 7227
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=a747456f7dfe6d304822adaf6443c4f8
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London

profiles:
  compute:
    pyload:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        pyload:
          denom: uakt
          amount: 100000
deployment:
  pyload:
    akash:
      profile: pyload
      count: 1
