version: "2.0"

services:
  headphones:
    image: linuxserver/headphones
    expose:
      - port: 8181
        as: 8181
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=b01c784d015279e4da00e04327385459
      - TZ=Etc/UTC

profiles:
  compute:
    headphones:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        headphones:
          denom: uakt
          amount: 100000
deployment:
  headphones:
    akash:
      profile: headphones
      count: 1
