version: "2.0"

services:
  webtop:
    image: linuxserver/webtop
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 3001
        as: 3001
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - DOCKER_MODS=linuxserver/mods:universal-internationalization
      - PASSWORD=57e52074ff99172ce2272d805ef389c1
      - LC_ALL=zh_CN.UTF-8
      - PGID=1000
      - PUID=1000
      - SUBFOLDER=/
      - TITLE=Webtop
      - TZ=Etc/UTC

profiles:
  compute:
    webtop:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        webtop:
          denom: uakt
          amount: 100000
deployment:
  webtop:
    akash:
      profile: webtop
      count: 1
