version: "2.0"

services:
  oraclelinux-extras:
    image: bitnami/oraclelinux-extras
    expose:

    env:

profiles:
  compute:
    oraclelinux-extras:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 8Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        oraclelinux-extras:
          denom: uakt
          amount: 100000
deployment:
  oraclelinux-extras:
    akash:
      profile: oraclelinux-extras
      count: 1
