version: "2.0"

services:
  fail2ban:
    image: linuxserver/fail2ban
    expose:
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=ed5c8f389818febe3135a7e6fabe46ca
      - TZ=Etc/UTC

profiles:
  compute:
    fail2ban:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        fail2ban:
          denom: uakt
          amount: 100000
deployment:
  fail2ban:
    akash:
      profile: fail2ban
      count: 1
