version: "2.0"

services:
  prowlarr:
    image: linuxserver/prowlarr
    expose:
      - port: 9696
        as: 9696
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=d6f8e9cad8f19682581041ec6c9871f2
      - TZ=Etc/UTC

profiles:
  compute:
    prowlarr:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        prowlarr:
          denom: uakt
          amount: 100000
deployment:
  prowlarr:
    akash:
      profile: prowlarr
      count: 1
