version: "2.0"

services:
  duckdns:
    image: linuxserver/duckdns
    expose:
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=9c2ca0723c37f1c093d00d8813db90c0
      - LOG_FILE=false
      - PGID=1000
      - PUID=1000
      - SUBDOMAINS=subdomain1,subdomain2
      - TOKEN=token
      - TZ=Etc/UTC

profiles:
  compute:
    duckdns:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        duckdns:
          denom: uakt
          amount: 100000
deployment:
  duckdns:
    akash:
      profile: duckdns
      count: 1
