version: "2.0"

services:
  projectsend:
    image: linuxserver/projectsend
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=4157c80da47e68570a5fc793773e03f3
      - MAX_UPLOAD=5000
      - TZ=Etc/UTC

profiles:
  compute:
    projectsend:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        projectsend:
          denom: uakt
          amount: 100000
deployment:
  projectsend:
    akash:
      profile: projectsend
      count: 1
