version: "2.0"

services:
  lollypop:
    image: linuxserver/lollypop
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 3001
        as: 3001
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=cdd73b8f5185716e8889e0fd84a8ee73
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC

profiles:
  compute:
    lollypop:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        lollypop:
          denom: uakt
          amount: 100000
deployment:
  lollypop:
    akash:
      profile: lollypop
      count: 1
