version: "2.0"

services:
  heimdall:
    image: linuxserver/heimdall
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 443
        as: 443
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=5a4926fe70c64a6c6c690721c4d35177
      - TZ=Etc/UTC

profiles:
  compute:
    heimdall:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        heimdall:
          denom: uakt
          amount: 100000
deployment:
  heimdall:
    akash:
      profile: heimdall
      count: 1
