version: "2.0"

services:
  daapd:
    image: linuxserver/daapd
    expose:
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=9c4bccc5bf69e60cc774be158111225e
      - TZ=Etc/UTC

profiles:
  compute:
    daapd:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        daapd:
          denom: uakt
          amount: 100000
deployment:
  daapd:
    akash:
      profile: daapd
      count: 1
