version: "2.0"

services:
  sickchill:
    image: linuxserver/sickchill
    expose:
      - port: 8081
        as: 8081
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=26536cccd917fc1d2a424942e939fb1b
      - TZ=Etc/UTC

profiles:
  compute:
    sickchill:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        sickchill:
          denom: uakt
          amount: 100000
deployment:
  sickchill:
    akash:
      profile: sickchill
      count: 1
