version: "2.0"

services:
  nntp2nntp:
    image: linuxserver/nntp2nntp
    expose:
      - port: 1563
        as: 1563
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=959c9b51646e81ed10f448f356d2bb37
      - PGID=1000
      - PGID=<yourGID>
      - PUID=1000
      - PUID=<yourUID>
      - TZ=Europe/London

profiles:
  compute:
    nntp2nntp:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        nntp2nntp:
          denom: uakt
          amount: 100000
deployment:
  nntp2nntp:
    akash:
      profile: nntp2nntp
      count: 1
