version: "2.0"

services:
  hydra:
    image: linuxserver/hydra
    expose:
      - port: 5075
        as: 5075
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=879e11dad922ef65c3c11b31aa7b6484
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London

profiles:
  compute:
    hydra:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        hydra:
          denom: uakt
          amount: 100000
deployment:
  hydra:
    akash:
      profile: hydra
      count: 1
