version: "2.0"

services:
  orangehrm:
    image: bitnami/orangehrm
    expose:

    env:

profiles:
  compute:
    orangehrm:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 8Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        orangehrm:
          denom: uakt
          amount: 100000
deployment:
  orangehrm:
    akash:
      profile: orangehrm
      count: 1
