version: "2.0"

services:
  cops:
    image: linuxserver/cops
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=2f1b89635c3cf53a4feb17c780e85eef
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC

profiles:
  compute:
    cops:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        cops:
          denom: uakt
          amount: 100000
deployment:
  cops:
    akash:
      profile: cops
      count: 1
