version: "2.0"

services:
  synclounge:
    image: linuxserver/synclounge
    expose:
      - port: 8088
        as: 8088
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - AUTH_LIST=plexuser1,plexuser2,email1,machineid1
      - AUTOJOIN_ENABLED=false
      - AUTOJOIN_ROOM=roomname
      - PASSWORD=4f3f988128f8ed6a1065eee05cb3e69b

profiles:
  compute:
    synclounge:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        synclounge:
          denom: uakt
          amount: 100000
deployment:
  synclounge:
    akash:
      profile: synclounge
      count: 1
