version: "2.0"

services:
  pairdrop:
    image: linuxserver/pairdrop
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=2cdd2d40174ec55a5a069c9c5af27108
      - RATE_LIMIT=false
      - RTC_CONFIG=
      - TZ=Etc/UTC
      - WS_FALLBACK=false

profiles:
  compute:
    pairdrop:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        pairdrop:
          denom: uakt
          amount: 100000
deployment:
  pairdrop:
    akash:
      profile: pairdrop
      count: 1
