version: "2.0"

services:
  fleet:
    image: linuxserver/fleet
    expose:
      - port: 8080
        as: 8080
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=6bc075ac5276e8334ded1f5c21931b2d
      - fleet_admin_authentication_type=DATABASE
      - fleet_admin_secret=randomstring
      - fleet_database_password=dbuserpassword
      - fleet_database_url=jdbc:mariadb://<url>:3306/fleet
      - fleet_database_username=fleet_user
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC

profiles:
  compute:
    fleet:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        fleet:
          denom: uakt
          amount: 100000
deployment:
  fleet:
    akash:
      profile: fleet
      count: 1
