version: "2.0"

services:
  piwigo:
    image: linuxserver/piwigo
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=3c5c8961a157bc011aab9d230c5d317b
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC

profiles:
  compute:
    piwigo:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        piwigo:
          denom: uakt
          amount: 100000
deployment:
  piwigo:
    akash:
      profile: piwigo
      count: 1
