version: "2.0"

services:
  sabnzbd:
    image: linuxserver/sabnzbd
    expose:
      - port: 8080
        as: 8080
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=5c64719fd0d496052be9d21542cd3ae2
      - TZ=Etc/UTC

profiles:
  compute:
    sabnzbd:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        sabnzbd:
          denom: uakt
          amount: 100000
deployment:
  sabnzbd:
    akash:
      profile: sabnzbd
      count: 1
