version: "2.0"

services:
  duplicati:
    image: linuxserver/duplicati
    expose:
      - port: 8200
        as: 8200
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - CLI_ARGS=
      - PASSWORD=d34e361bbf1c1669c4ac7ad7e702e964
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC

profiles:
  compute:
    duplicati:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        duplicati:
          denom: uakt
          amount: 100000
deployment:
  duplicati:
    akash:
      profile: duplicati
      count: 1
