version: "2.0"

services:
  ngircd:
    image: linuxserver/ngircd
    expose:
      - port: 6667
        as: 6667
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=25b4cd891735d1cddad761f43ca0fd6b
      - TZ=Etc/UTC

profiles:
  compute:
    ngircd:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        ngircd:
          denom: uakt
          amount: 100000
deployment:
  ngircd:
    akash:
      profile: ngircd
      count: 1
