version: "2.0"

services:
  booksonic:
    image: linuxserver/booksonic
    expose:
      - port: 4040
        as: 4040
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - CONTEXT_PATH=url-base
      - PASSWORD=9ebda94d13b4892a9c6496889be94f22
      - TZ=Europe/London

profiles:
  compute:
    booksonic:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        booksonic:
          denom: uakt
          amount: 100000
deployment:
  booksonic:
    akash:
      profile: booksonic
      count: 1
