version: "2.0"

services:
  emby:
    image: linuxserver/emby
    expose:
      - port: 8096
        as: 8096
        to:
          - global: true
      - port: 8920
        as: 8920
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=36bf1682cf17667864411c75e8424a46
      - TZ=Etc/UTC

profiles:
  compute:
    emby:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        emby:
          denom: uakt
          amount: 100000
deployment:
  emby:
    akash:
      profile: emby
      count: 1
