version: "2.0"

services:
  homeassistant:
    image: linuxserver/homeassistant
    expose:
      - port: 8123
        as: 8123
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=ac98407b1da6810211294c8da2cf1990
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC

profiles:
  compute:
    homeassistant:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        homeassistant:
          denom: uakt
          amount: 100000
deployment:
  homeassistant:
    akash:
      profile: homeassistant
      count: 1
