version: "2.0"

services:
  tester:
    image: linuxserver/tester
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=575d04c633b2cce1e762e2b6dc620951
      - URL=http://google.com

profiles:
  compute:
    tester:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        tester:
          denom: uakt
          amount: 100000
deployment:
  tester:
    akash:
      profile: tester
      count: 1
