version: "2.0"

services:
  chevereto:
    image: linuxserver/chevereto
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 443
        as: 443
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=835f1c9ae11a0b78d0011f4cc9a014ab
      - PGID=1000
      - PUID=1000
      - TZ=<TZ>

profiles:
  compute:
    chevereto:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        chevereto:
          denom: uakt
          amount: 100000
deployment:
  chevereto:
    akash:
      profile: chevereto
      count: 1
