version: "2.0"

services:
  raneto:
    image: linuxserver/raneto
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=77b30666c67e85b9003b360ae4d25a0b
      - TZ=Etc/UTC

profiles:
  compute:
    raneto:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        raneto:
          denom: uakt
          amount: 100000
deployment:
  raneto:
    akash:
      profile: raneto
      count: 1
