version: "2.0"

services:
  airsonic:
    image: linuxserver/airsonic
    expose:
      - port: 4040
        as: 4040
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - CONTEXT_PATH=<URL_BASE>
      - PASSWORD=a9c0306a36029dc5f429c1be992a7344
      - JAVA_OPTS=<options>
      - JAVA_OPTS="-Xmx256m
      - TZ=Europe/London

profiles:
  compute:
    airsonic:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        airsonic:
          denom: uakt
          amount: 100000
deployment:
  airsonic:
    akash:
      profile: airsonic
      count: 1
