version: "2.0"

services:
  kdenlive:
    image: linuxserver/kdenlive
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 3001
        as: 3001
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=40a65c5bf0e9e6f89d84e9d64678df7f
      - PGID=1000
      - PUID=1000
      - SUBFOLDER=/
      - TZ=Etc/UTC

profiles:
  compute:
    kdenlive:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        kdenlive:
          denom: uakt
          amount: 100000
deployment:
  kdenlive:
    akash:
      profile: kdenlive
      count: 1
