version: "2.0"

services:
  nextcloud:
    image: linuxserver/nextcloud
    expose:
      - port: 443
        as: 443
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=45656e70f7d0bfc6eb70ad9316b76cd0
      - TZ=Etc/UTC

profiles:
  compute:
    nextcloud:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        nextcloud:
          denom: uakt
          amount: 100000
deployment:
  nextcloud:
    akash:
      profile: nextcloud
      count: 1
