version: "2.0"

services:
  radarr:
    image: linuxserver/radarr
    expose:
      - port: 7878
        as: 7878
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=a62ccd1a0087f1d2067af04e46ddb26d
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC

profiles:
  compute:
    radarr:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        radarr:
          denom: uakt
          amount: 100000
deployment:
  radarr:
    akash:
      profile: radarr
      count: 1
