version: "2.0"

services:
  requestrr:
    image: linuxserver/requestrr
    expose:
      - port: 4545
        as: 4545
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=44278faf91c4217665b09d64a5267bbb
      - TZ=Europe/London

profiles:
  compute:
    requestrr:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        requestrr:
          denom: uakt
          amount: 100000
deployment:
  requestrr:
    akash:
      profile: requestrr
      count: 1
