version: "2.0"

services:
  quassel-core:
    image: linuxserver/quassel-core
    expose:
      - port: 4242
        as: 4242
        to:
          - global: true
      - port: 4242
        as: 4242
        to:
          - global: true
      - port: 10113
        as: 10113
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - AUTH_AUTHENTICATOR=Database
      - DB_BACKEND=SQLite
      - PASSWORD=ff9958324d55f327c32cb96e59c9d50d
      - RUN_OPTS='--config-from-environment'
      - RUN_OPTS=--config-from-environment
      - TZ=Etc/UTC
      - TZ=Europe/London

profiles:
  compute:
    quassel-core:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        quassel-core:
          denom: uakt
          amount: 100000
deployment:
  quassel-core:
    akash:
      profile: quassel-core
      count: 1
