version: "2.0"

services:
  grocy:
    image: linuxserver/grocy
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=527020305aed1ec19af4da89299fb049
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC

profiles:
  compute:
    grocy:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        grocy:
          denom: uakt
          amount: 100000
deployment:
  grocy:
    akash:
      profile: grocy
      count: 1
