version: "2.0"

services:
  dokuwiki:
    image: linuxserver/dokuwiki
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 443
        as: 443
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=8c2148b7010c90b076d207a6f197fc8e
      - TZ=Etc/UTC

profiles:
  compute:
    dokuwiki:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        dokuwiki:
          denom: uakt
          amount: 100000
deployment:
  dokuwiki:
    akash:
      profile: dokuwiki
      count: 1
