version: "2.0"

services:
  rdesktop:
    image: linuxserver/rdesktop
    expose:
      - port: 3389
        as: 3389
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=8df1565a2e8bdbc3858f56fac7053244
      - TZ=Etc/UTC

profiles:
  compute:
    rdesktop:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        rdesktop:
          denom: uakt
          amount: 100000
deployment:
  rdesktop:
    akash:
      profile: rdesktop
      count: 1
