version: "2.0"

services:
  paperless-ngx:
    image: linuxserver/paperless-ngx
    expose:
      - port: 8000
        as: 8000
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=02e3114d90f8a1ca5c039e072790233e
      - REDIS_URL=
      - TZ=America/New_York

profiles:
  compute:
    paperless-ngx:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        paperless-ngx:
          denom: uakt
          amount: 100000
deployment:
  paperless-ngx:
    akash:
      profile: paperless-ngx
      count: 1
