version: "2.0"

services:
  thelounge:
    image: linuxserver/thelounge
    expose:
      - port: 9000
        as: 9000
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=e3f7da200ac1b1ba6742b00b68fcc467
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC

profiles:
  compute:
    thelounge:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        thelounge:
          denom: uakt
          amount: 100000
deployment:
  thelounge:
    akash:
      profile: thelounge
      count: 1
