version: "2.0"

services:
  mylar:
    image: linuxserver/mylar
    expose:
      - port: 8090
        as: 8090
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=f3de8e4086ab076ca6b366b574ff4fdd

profiles:
  compute:
    mylar:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        mylar:
          denom: uakt
          amount: 100000
deployment:
  mylar:
    akash:
      profile: mylar
      count: 1
