version: "2.0"

services:
  your_spotify:
    image: linuxserver/your_spotify
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 443
        as: 443
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - APP_URL=http://localhost
      - CORS=http://localhost:80,https://localhost:443
      - PASSWORD=f544dc720041863fc86958c842a0bde6
      - MONGO_ENDPOINT=mongodb://mongo:27017/your_spotify
      - SPOTIFY_PUBLIC=
      - SPOTIFY_SECRET=
      - TZ=Etc/UTC

profiles:
  compute:
    your_spotify:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        your_spotify:
          denom: uakt
          amount: 100000
deployment:
  your_spotify:
    akash:
      profile: your_spotify
      count: 1
