version: "2.0"

services:
  syslog-ng:
    image: linuxserver/syslog-ng
    expose:
      - port: 5514
        as: 5514
        to:
          - global: true
      - port: 6601
        as: 6601
        to:
          - global: true
      - port: 6514
        as: 6514
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=18fae2c5b1765586c1fdfb541def31ee
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC

profiles:
  compute:
    syslog-ng:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        syslog-ng:
          denom: uakt
          amount: 100000
deployment:
  syslog-ng:
    akash:
      profile: syslog-ng
      count: 1
