version: "2.0"

services:
  smokeping:
    image: linuxserver/smokeping
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=79a23ddb139c47515b5a06b3ab1af1f0
      - TZ=Etc/UTC

profiles:
  compute:
    smokeping:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        smokeping:
          denom: uakt
          amount: 100000
deployment:
  smokeping:
    akash:
      profile: smokeping
      count: 1
