version: "2.0"

services:
  tvheadend:
    image: linuxserver/tvheadend
    expose:
      - port: 9981
        as: 9981
        to:
          - global: true
      - port: 9982
        as: 9982
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=078505a875c0680ac6efcf81cdf17172
      - RUN_OPTS=
      - TZ=Etc/UTC

profiles:
  compute:
    tvheadend:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        tvheadend:
          denom: uakt
          amount: 100000
deployment:
  tvheadend:
    akash:
      profile: tvheadend
      count: 1
