version: "2.0"

services:
  papermerge:
    image: linuxserver/papermerge
    expose:
      - port: 8000
        as: 8000
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=c62364df36a7e1a21b1f76e45f148ab8
      - REDIS_URL=
      - TZ=Etc/UTC

profiles:
  compute:
    papermerge:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        papermerge:
          denom: uakt
          amount: 100000
deployment:
  papermerge:
    akash:
      profile: papermerge
      count: 1
