version: "2.0"

services:
  kasm:
    image: linuxserver/kasm
    expose:
      - port: 4443
        as: 4443
        to:
          - global: true
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 443
        as: 443
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - DOCKER_HUB_PASSWORD=PASS
      - DOCKER_HUB_USERNAME=USER
      - DOCKER_MTU=1500
      - PASSWORD=c7d0a104d276f2ac13d5ffaecb298b14
      - KASM_PORT=443

profiles:
  compute:
    kasm:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        kasm:
          denom: uakt
          amount: 100000
deployment:
  kasm:
    akash:
      profile: kasm
      count: 1
