version: "2.0"

services:
  znc:
    image: linuxserver/znc
    expose:
      - port: 6501
        as: 6501
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=cc9bc5af7e9fb4ad8538ea6888a5643f
      - TZ=Etc/UTC

profiles:
  compute:
    znc:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        znc:
          denom: uakt
          amount: 100000
deployment:
  znc:
    akash:
      profile: znc
      count: 1
