version: "2.0"

services:
  jackett:
    image: linuxserver/jackett
    expose:
      - port: 9117
        as: 9117
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - AUTO_UPDATE=true
      - PASSWORD=66bfda304ffd69342d9f833c5dd38cf2
      - PGID=1000
      - PUID=1000
      - RUN_OPTS=
      - TZ=Etc/UTC

profiles:
  compute:
    jackett:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        jackett:
          denom: uakt
          amount: 100000
deployment:
  jackett:
    akash:
      profile: jackett
      count: 1
