version: "2.0"

services:
  github-desktop:
    image: linuxserver/github-desktop
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 3001
        as: 3001
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=54c134e0f9888e389f79b119fa427a05
      - TZ=Etc/UTC

profiles:
  compute:
    github-desktop:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        github-desktop:
          denom: uakt
          amount: 100000
deployment:
  github-desktop:
    akash:
      profile: github-desktop
      count: 1
