version: "2.0"

services:
  pyload-ng:
    image: linuxserver/pyload-ng
    expose:
      - port: 8000
        as: 8000
        to:
          - global: true
      - port: 9666
        as: 9666
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=37aedcbe827cda4f90a5766e7607b3c0
      - TZ=Etc/UTC

profiles:
  compute:
    pyload-ng:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        pyload-ng:
          denom: uakt
          amount: 100000
deployment:
  pyload-ng:
    akash:
      profile: pyload-ng
      count: 1
