version: "2.0"

services:
  limnoria:
    image: linuxserver/limnoria
    expose:
      - port: 8080
        as: 8080
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=69072e8ed11fe801374ba75308ae699c
      - TZ=Etc/UTC

profiles:
  compute:
    limnoria:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        limnoria:
          denom: uakt
          amount: 100000
deployment:
  limnoria:
    akash:
      profile: limnoria
      count: 1
