version: "2.0"

services:
  habridge:
    image: linuxserver/habridge
    expose:
      - port: 8080
        as: 8080
        to:
          - global: true
      - port: 50000
        as: 50000
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=120d1eeafad9ea63b2974aba0b44faec
      - SEC_KEY="<Your
      - SEC_KEY=<Your
      - TZ=Etc/UTC

profiles:
  compute:
    habridge:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        habridge:
          denom: uakt
          amount: 100000
deployment:
  habridge:
    akash:
      profile: habridge
      count: 1
