version: "2.0"

services:
  boinc:
    image: linuxserver/boinc
    expose:
      - port: 8080
        as: 8080
        to:
          - global: true
      - port: 8181
        as: 8181
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=0f163bb157507dd69bad5b063a7349cb
      - PASSWORD=
      - TZ=Etc/UTC

profiles:
  compute:
    boinc:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        boinc:
          denom: uakt
          amount: 100000
deployment:
  boinc:
    akash:
      profile: boinc
      count: 1
