version: "2.0"

services:
  babybuddy:
    image: linuxserver/babybuddy
    expose:
      - port: 8000
        as: 8000
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - CSRF_TRUSTED_ORIGINS=http://127.0.0.1:8000,https://babybuddy.domain.com
      - PASSWORD=2e06b3df354597f682e0c22ba4a33b30
      - TZ=Etc/UTC

profiles:
  compute:
    babybuddy:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        babybuddy:
          denom: uakt
          amount: 100000
deployment:
  babybuddy:
    akash:
      profile: babybuddy
      count: 1
