version: "2.0"

services:
  scrutiny:
    image: linuxserver/scrutiny
    expose:
      - port: 8080
        as: 8080
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=0247956903c42e9aa00aa9464dafb842
      - PGID=1000
      - PUID=1000
      - SCRUTINY_API_ENDPOINT=http://localhost:8080
      - SCRUTINY_COLLECTOR=true
      - SCRUTINY_WEB=true
      - TZ=Europe/London

profiles:
  compute:
    scrutiny:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        scrutiny:
          denom: uakt
          amount: 100000
deployment:
  scrutiny:
    akash:
      profile: scrutiny
      count: 1
