version: "2.0"

services:
  sickrage:
    image: linuxserver/sickrage
    expose:
      - port: 8081
        as: 8081
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London

profiles:
  compute:
    sickrage:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        sickrage:
          denom: uakt
          amount: 100000
deployment:
  sickrage:
    akash:
      profile: sickrage
      count: 1
