version: "2.0"

services:
  librespeed:
    image: linuxserver/librespeed
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - CUSTOM_RESULTS=false
      - DB_HOSTNAME=DB_HOSTNAME
      - DB_NAME=DB_NAME
      - DB_PASSWORD=DB_PASSWORD
      - DB_PORT=DB_PORT
      - DB_TYPE=sqlite
      - DB_USERNAME=DB_USERNAME
      - PASSWORD=85108645b3d3b72900bc987f899f140e
      - IPINFO_APIKEY=ACCESS_TOKEN
      - PASSWORD=PASSWORD
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC

profiles:
  compute:
    librespeed:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        librespeed:
          denom: uakt
          amount: 100000
deployment:
  librespeed:
    akash:
      profile: librespeed
      count: 1
