version: "2.0"

services:
  swag:
    image: linuxserver/swag
    expose:
      - port: 443
        as: 443
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - CERTPROVIDER=
      - DNSPLUGIN=cloudflare
      - EMAIL=
      - EXTRA_DOMAINS=
      - ONLY_SUBDOMAINS=false
      - PGID=1000
      - PROPAGATION=
      - PUID=1000
      - STAGING=false
      - SUBDOMAINS=www,
      - TZ=Etc/UTC

profiles:
  compute:
    swag:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        swag:
          denom: uakt
          amount: 100000
deployment:
  swag:
    akash:
      profile: swag
      count: 1
