version: "2.0"

services:
  calibre:
    image: linuxserver/calibre
    expose:
      - port: 8080
        as: 8080
        to:
          - global: true
      - port: 8181
        as: 8181
        to:
          - global: true
      - port: 8081
        as: 8081
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - CLI_ARGS=
      - PASSWORD=fa581bc717975f8ba35ab7309c030b56
      - PASSWORD=
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC

profiles:
  compute:
    calibre:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        calibre:
          denom: uakt
          amount: 100000
deployment:
  calibre:
    akash:
      profile: calibre
      count: 1
