version: "2.0"

services:
  dillinger:
    image: linuxserver/dillinger
    expose:
      - port: 8080
        as: 8080
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=4f143d45ad1825305dd88cac72d12eb9
      - TZ=Etc/UTC

profiles:
  compute:
    dillinger:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        dillinger:
          denom: uakt
          amount: 100000
deployment:
  dillinger:
    akash:
      profile: dillinger
      count: 1
