version: "2.0"

services:
  oracle-8-desktop:
    image: kasmweb/oracle-8-desktop
    expose:

    env:

profiles:
  compute:
    oracle-8-desktop:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 8Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        oracle-8-desktop:
          denom: uakt
          amount: 100000
deployment:
  oracle-8-desktop:
    akash:
      profile: oracle-8-desktop
      count: 1
