version: "2.0"

services:
  pylon:
    image: linuxserver/pylon
    expose:
      - port: 3131
        as: 3131
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=95c36b11b833f5f9cbd967b9dfbb7d5e
      - GITURL=https://github.com/linuxserver/docker-pylon.git
      - PGID=1000
      - PUID=1000
      - PYPASS=mypass
      - PYUSER=myuser
      - TZ=Etc/UTC

profiles:
  compute:
    pylon:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        pylon:
          denom: uakt
          amount: 100000
deployment:
  pylon:
    akash:
      profile: pylon
      count: 1
