version: "2.0"

services:
  mcmyadmin2:
    image: linuxserver/mcmyadmin2
    expose:
      - port: 8080
        as: 8080
        to:
          - global: true
      - port: 25565
        as: 25565
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true
      - port: 8080
        as: 8080
        to:
          - global: true
      - port: 25565
        as: 25565
        to:
          - global: true

    env:

profiles:
  compute:
    mcmyadmin2:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        mcmyadmin2:
          denom: uakt
          amount: 100000
deployment:
  mcmyadmin2:
    akash:
      profile: mcmyadmin2
      count: 1
