version: "2.0"

services:
  ldap-auth:
    image: linuxserver/ldap-auth
    expose:
      - port: 8888
        as: 8888
        to:
          - global: true
      - port: 9000
        as: 9000
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - CERTFILE=
      - FERNETKEY=
      - PASSWORD=d4e48e6096cec348ea890dc2a35cd31d
      - KEYFILE=

profiles:
  compute:
    ldap-auth:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        ldap-auth:
          denom: uakt
          amount: 100000
deployment:
  ldap-auth:
    akash:
      profile: ldap-auth
      count: 1
