version: "2.0"

services:
  codimd:
    image: linuxserver/codimd
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - DB_HOST=<hostname
      - DB_NAME=codimd
      - DB_PASS=<secret
      - DB_PORT=3306
      - DB_USER=codimd
      - PASSWORD=6ff98fda697666846400ffcb989e2d74
      - TZ=Europe/London

profiles:
  compute:
    codimd:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        codimd:
          denom: uakt
          amount: 100000
deployment:
  codimd:
    akash:
      profile: codimd
      count: 1
