version: "2.0"

services:
  foldingathome:
    image: linuxserver/foldingathome
    expose:
      - port: 7396
        as: 7396
        to:
          - global: true
      - port: 36330
        as: 36330
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=edcd171c50fd695ea50f27bc22a849c4
      - TZ=Etc/UTC

profiles:
  compute:
    foldingathome:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        foldingathome:
          denom: uakt
          amount: 100000
deployment:
  foldingathome:
    akash:
      profile: foldingathome
      count: 1
