version: "2.0"

services:
  nzbhydra2:
    image: linuxserver/nzbhydra2
    expose:
      - port: 5076
        as: 5076
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=a7dc770a3b65147eaec88ba4789feef2
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC

profiles:
  compute:
    nzbhydra2:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        nzbhydra2:
          denom: uakt
          amount: 100000
deployment:
  nzbhydra2:
    akash:
      profile: nzbhydra2
      count: 1
