version: "2.0"

services:
  musicbrainz:
    image: linuxserver/musicbrainz
    expose:
      - port: 5000
        as: 5000
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - BRAINZCODE=<code
      - PASSWORD=65a3004fb02ba3b4c3732a889d66e87b
      - NPROC=<parameter>
      - TZ=Europe/London
      - WEBADDRESS=<ip

profiles:
  compute:
    musicbrainz:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        musicbrainz:
          denom: uakt
          amount: 100000
deployment:
  musicbrainz:
    akash:
      profile: musicbrainz
      count: 1
