version: "2.0"

services:
  openvpn-as:
    image: linuxserver/openvpn-as
    expose:
      - port: 943
        as: 943
        to:
          - global: true
      - port: 9443
        as: 9443
        to:
          - global: true
      - port: 1194
        as: 1194
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=3b80bb9d534cd06620dcb61eda6f0680
      - INTERFACE=eth0
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London

profiles:
  compute:
    openvpn-as:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        openvpn-as:
          denom: uakt
          amount: 100000
deployment:
  openvpn-as:
    akash:
      profile: openvpn-as
      count: 1
