version: "2.0"

services:
  nzbget:
    image: linuxserver/nzbget
    expose:
      - port: 6789
        as: 6789
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=2406b8dc2f4c16aca4d1889c5ea5d32d
      - NZBGET_PASS=tegbzn6789
      - NZBGET_USER=nzbget
      - TZ=Europe/London

profiles:
  compute:
    nzbget:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        nzbget:
          denom: uakt
          amount: 100000
deployment:
  nzbget:
    akash:
      profile: nzbget
      count: 1
