version: "2.0"

services:
  mariadb:
    image: linuxserver/mariadb
    expose:
      - port: 3306
        as: 3306
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=d720906327d03e537fb9c52fd77a4e37
      - MYSQL_DATABASE=USER_DB_NAME
      - MYSQL_PASSWORD=DATABASE_PASSWORD
      - MYSQL_ROOT_PASSWORD=ROOT_ACCESS_PASSWORD
      - MYSQL_USER=MYSQL_USER
      - REMOTE_SQL=http://URL1/your.sql,https://URL2/your.sql
      - TZ=Etc/UTC

profiles:
  compute:
    mariadb:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        mariadb:
          denom: uakt
          amount: 100000
deployment:
  mariadb:
    akash:
      profile: mariadb
      count: 1
