version: "2.0"

services:
  clarkson:
    image: linuxserver/clarkson
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - ENABLE_REGISTRATIONS=<true/false>
      - PASSWORD=56e382097fca39209fb4229988f2910c
      - MYSQL_HOST=<mysql_host>
      - MYSQL_PASSWORD=<mysql_password>
      - MYSQL_USERNAME=<mysql_username>
      - TZ=Europe/London

profiles:
  compute:
    clarkson:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        clarkson:
          denom: uakt
          amount: 100000
deployment:
  clarkson:
    akash:
      profile: clarkson
      count: 1
