version: "2.0"

services:
  organizr:
    image: linuxserver/organizr
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=4ee44240bba2b8e760032319239efea5
      - PGID=1000
      - PUID=1000
      - TZ=<your

profiles:
  compute:
    organizr:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        organizr:
          denom: uakt
          amount: 100000
deployment:
  organizr:
    akash:
      profile: organizr
      count: 1
