version: "2.0"

services:
  jellyfin:
    image: linuxserver/jellyfin
    expose:
      - port: 8096
        as: 8096
        to:
          - global: true
      - port: 8920
        as: 8920
        to:
          - global: true
      - port: 7359
        as: 7359
        to:
          - global: true
      - port: 1900
        as: 1900
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true
      - port: 7359
        as: 7359
        to:
          - global: true
      - port: 1900
        as: 1900
        to:
          - global: true

    env:
      - PASSWORD=55084f3cbcf7e7eba3a9d3cad99b22b0
      - JELLYFIN_PublishedServerUrl=192.168.0.5
      - TZ=Etc/UTC

profiles:
  compute:
    jellyfin:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        jellyfin:
          denom: uakt
          amount: 100000
deployment:
  jellyfin:
    akash:
      profile: jellyfin
      count: 1
