version: "2.0"

services:
  grav:
    image: linuxserver/grav
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=e4b2faa2f0c58c9758f894e45d6578ff
      - TZ=Etc/UTC

profiles:
  compute:
    grav:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        grav:
          denom: uakt
          amount: 100000
deployment:
  grav:
    akash:
      profile: grav
      count: 1
