version: "2.0"

services:
  firefox:
    image: linuxserver/firefox
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 3001
        as: 3001
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=afba6ede7bc1e320953ac6f5c442ea36
      - TZ=Etc/UTC

profiles:
  compute:
    firefox:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        firefox:
          denom: uakt
          amount: 100000
deployment:
  firefox:
    akash:
      profile: firefox
      count: 1
