version: "2.0"

services:
  orange-pi-lite-alpine-node:
    image: balenalib/orange-pi-lite-alpine-node
    expose:

    env:

profiles:
  compute:
    orange-pi-lite-alpine-node:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 8Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        orange-pi-lite-alpine-node:
          denom: uakt
          amount: 100000
deployment:
  orange-pi-lite-alpine-node:
    akash:
      profile: orange-pi-lite-alpine-node
      count: 1
