version: "2.0"

services:
  pydio-cells:
    image: linuxserver/pydio-cells
    expose:
      - port: 8080
        as: 8080
        to:
          - global: true
      - port: 33060
        as: 33060
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - EXTERNALURL=yourdomain.url
      - PASSWORD=18ac2783c51056e78162156606571a45
      - SERVER_IP=0.0.0.0
      - TZ=Etc/UTC

profiles:
  compute:
    pydio-cells:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        pydio-cells:
          denom: uakt
          amount: 100000
deployment:
  pydio-cells:
    akash:
      profile: pydio-cells
      count: 1
