version: "2.0"

services:
  booksonic-air:
    image: linuxserver/booksonic-air
    expose:
      - port: 4040
        as: 4040
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - CONTEXT_PATH=url-base
      - PASSWORD=bdd05c70fe3e6efb34de9ee461b2956e
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC

profiles:
  compute:
    booksonic-air:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        booksonic-air:
          denom: uakt
          amount: 100000
deployment:
  booksonic-air:
    akash:
      profile: booksonic-air
      count: 1
