version: "2.0"

services:
  filezilla:
    image: linuxserver/filezilla
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 3001
        as: 3001
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=b9bc045daf82892bc728cffb5c49bc66
      - TZ=Etc/UTC

profiles:
  compute:
    filezilla:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        filezilla:
          denom: uakt
          amount: 100000
deployment:
  filezilla:
    akash:
      profile: filezilla
      count: 1
