version: "2.0"

services:
  filezilla:
    image: linuxserver/filezilla
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 3001
        as: 3001
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=d1ad4bed7d68801d4c7629a4440cadab
      - TZ=Etc/UTC

profiles:
  compute:
    filezilla:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        filezilla:
          denom: uakt
          amount: 100000
deployment:
  filezilla:
    akash:
      profile: filezilla
      count: 1
