version: "2.0"

services:
  mysql:
    image: linuxserver/mysql
    expose:
      - port: 3306
        as: 3306
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - MYSQL_ROOT_PASSWORD=MYSQL_ROOT_PASSWORD
      - MYSQL_ROOT_PASSWORD=<DATABASE
      - PGID=PGID
      - PGID=<GID>
      - PUID=PUID
      - PUID=<UID>

profiles:
  compute:
    mysql:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        mysql:
          denom: uakt
          amount: 100000
deployment:
  mysql:
    akash:
      profile: mysql
      count: 1
