version: "2.0"

services:
  mods:
    image: linuxserver/mods
    expose:
      - port: 6789
        as: 6789
        to:
          - global: true

    env:
      - DOCKER_MODS=taisun/nzbget-mod:latest
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London

profiles:
  compute:
    mods:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        mods:
          denom: uakt
          amount: 100000
deployment:
  mods:
    akash:
      profile: mods
      count: 1
