version: "2.0"

services:
  mylar3:
    image: linuxserver/mylar3
    expose:
      - port: 8090
        as: 8090
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=e0cd6c86e20ba0898957df5dc9551ae3
      - TZ=Etc/UTC

profiles:
  compute:
    mylar3:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        mylar3:
          denom: uakt
          amount: 100000
deployment:
  mylar3:
    akash:
      profile: mylar3
      count: 1
