version: "2.0"

services:
  bazarr:
    image: linuxserver/bazarr
    expose:
      - port: 6767
        as: 6767
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=bc1aabdbb002e9ca097f5868f414a66d
      - TZ=Etc/UTC

profiles:
  compute:
    bazarr:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        bazarr:
          denom: uakt
          amount: 100000
deployment:
  bazarr:
    akash:
      profile: bazarr
      count: 1
