version: "2.0"

services:
  chromium:
    image: linuxserver/chromium
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 3001
        as: 3001
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - CHROME_CLI=https://www.linuxserver.io/
      - PASSWORD=2730f0c13c65398b9fce47da6525cffd
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC

profiles:
  compute:
    chromium:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        chromium:
          denom: uakt
          amount: 100000
deployment:
  chromium:
    akash:
      profile: chromium
      count: 1
