version: "2.0"

services:
  unifi:
    image: linuxserver/unifi
    expose:
      - port: 3478
        as: 3478
        to:
          - global: true
      - port: 10001
        as: 10001
        to:
          - global: true
      - port: 8080
        as: 8080
        to:
          - global: true
      - port: 8081
        as: 8081
        to:
          - global: true
      - port: 8443
        as: 8443
        to:
          - global: true
      - port: 8843
        as: 8843
        to:
          - global: true
      - port: 8880
        as: 8880
        to:
          - global: true
      - port: 6789
        as: 6789
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PGID=PGID
      - PGID=<gid>
      - PUID=PUID
      - PUID=<uid>

profiles:
  compute:
    unifi:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        unifi:
          denom: uakt
          amount: 100000
deployment:
  unifi:
    akash:
      profile: unifi
      count: 1
