version: "2.0"

services:
  lidarr:
    image: linuxserver/lidarr
    expose:
      - port: 8686
        as: 8686
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=5ec1612cf73f36279de5e856fc932fcc
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC

profiles:
  compute:
    lidarr:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        lidarr:
          denom: uakt
          amount: 100000
deployment:
  lidarr:
    akash:
      profile: lidarr
      count: 1
