version: "2.0"

services:
  freshrss:
    image: linuxserver/freshrss
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=63754f4f0b212acbe6c4857540cbb3fa
      - TZ=Etc/UTC

profiles:
  compute:
    freshrss:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        freshrss:
          denom: uakt
          amount: 100000
deployment:
  freshrss:
    akash:
      profile: freshrss
      count: 1
