version: "2.0"

services:
  sickgear:
    image: linuxserver/sickgear
    expose:
      - port: 8081
        as: 8081
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=5e7345bd3d1e37d7855fea7046e55004
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC

profiles:
  compute:
    sickgear:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        sickgear:
          denom: uakt
          amount: 100000
deployment:
  sickgear:
    akash:
      profile: sickgear
      count: 1
