version: "2.0"

services:
  adguardhome-sync:
    image: linuxserver/adguardhome-sync
    expose:
      - port: 8080
        as: 8080
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - CONFIGFILE=/config/adguardhome-sync.yaml
      - PASSWORD=4407ba52ff5805592b96f38836ddedfb
      - TZ=Etc/UTC

profiles:
  compute:
    adguardhome-sync:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        adguardhome-sync:
          denom: uakt
          amount: 100000
deployment:
  adguardhome-sync:
    akash:
      profile: adguardhome-sync
      count: 1
