version: "2.0"

services:
  changedetection.io:
    image: linuxserver/changedetection.io
    expose:
      - port: 5000
        as: 5000
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - BASE_URL=
      - PASSWORD=401196b9113393aaaa1a05cc7d6cf969
      - TZ=Etc/UTC

profiles:
  compute:
    changedetection.io:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        changedetection.io:
          denom: uakt
          amount: 100000
deployment:
  changedetection.io:
    akash:
      profile: changedetection.io
      count: 1
