version: "2.0"

services:
  wikijs:
    image: linuxserver/wikijs
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - DB_HOST=
      - DB_NAME=
      - DB_PASS=
      - DB_PORT=
      - DB_TYPE=sqlite
      - DB_USER=
      - PASSWORD=9b23c46547cc119116849ba0dbc88eb0
      - TZ=Etc/UTC

profiles:
  compute:
    wikijs:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        wikijs:
          denom: uakt
          amount: 100000
deployment:
  wikijs:
    akash:
      profile: wikijs
      count: 1
