version: "2.0"

services:
  doublecommander:
    image: linuxserver/doublecommander
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 3001
        as: 3001
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=044050323a1f678e3ff6f9f13e0f79c7
      - TZ=Etc/UTC

profiles:
  compute:
    doublecommander:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        doublecommander:
          denom: uakt
          amount: 100000
deployment:
  doublecommander:
    akash:
      profile: doublecommander
      count: 1
