version: "2.0"

services:
  ubooquity:
    image: linuxserver/ubooquity
    expose:
      - port: 2202
        as: 2202
        to:
          - global: true
      - port: 2203
        as: 2203
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=319d8db35abda7226809e4a7dfcc29e1
      - MAXMEM=
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC

profiles:
  compute:
    ubooquity:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        ubooquity:
          denom: uakt
          amount: 100000
deployment:
  ubooquity:
    akash:
      profile: ubooquity
      count: 1
