version: "2.0"

services:
  blender:
    image: linuxserver/blender
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 3001
        as: 3001
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=c04402199062cce6276a617af8282e9c
      - SUBFOLDER=/
      - TZ=Etc/UTC

profiles:
  compute:
    blender:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        blender:
          denom: uakt
          amount: 100000
deployment:
  blender:
    akash:
      profile: blender
      count: 1
