version: "2.0"

services:
  ipfs:
    image: linuxserver/ipfs
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 4001
        as: 4001
        to:
          - global: true
      - port: 5001
        as: 5001
        to:
          - global: true
      - port: 8080
        as: 8080
        to:
          - global: true
      - port: 443
        as: 443
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=1fa29a28afa93241b4ce22e07f1b3275
      - TZ=Europe/London

profiles:
  compute:
    ipfs:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        ipfs:
          denom: uakt
          amount: 100000
deployment:
  ipfs:
    akash:
      profile: ipfs
      count: 1
