version: "2.0"

services:
  lazylibrarian:
    image: linuxserver/lazylibrarian
    expose:
      - port: 5299
        as: 5299
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - DOCKER_MODS=linuxserver/calibre-web:calibre|linuxserver/mods:lazylibrarian-ffmpeg
      - PASSWORD=18e3809c39c3ef405d128f8b468a1229
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC

profiles:
  compute:
    lazylibrarian:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        lazylibrarian:
          denom: uakt
          amount: 100000
deployment:
  lazylibrarian:
    akash:
      profile: lazylibrarian
      count: 1
