version: "2.0"

services:
  gazee:
    image: linuxserver/gazee
    expose:
      - port: 4242
        as: 4242
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:

profiles:
  compute:
    gazee:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        gazee:
          denom: uakt
          amount: 100000
deployment:
  gazee:
    akash:
      profile: gazee
      count: 1
