version: "2.0"

services:
  ddclient:
    image: linuxserver/ddclient
    expose:
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=07d93b212c26cae81fbfd23a47c0964f
      - TZ=Etc/UTC

profiles:
  compute:
    ddclient:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        ddclient:
          denom: uakt
          amount: 100000
deployment:
  ddclient:
    akash:
      profile: ddclient
      count: 1
