version: "2.0"

services:
  syncthing:
    image: linuxserver/syncthing
    expose:
      - port: 8384
        as: 8384
        to:
          - global: true
      - port: 22000
        as: 22000
        to:
          - global: true
      - port: 22000
        as: 22000
        to:
          - global: true
      - port: 21027
        as: 21027
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=f38a8330608fd9d3c699b20ac12f8681
      - TZ=Etc/UTC

profiles:
  compute:
    syncthing:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        syncthing:
          denom: uakt
          amount: 100000
deployment:
  syncthing:
    akash:
      profile: syncthing
      count: 1
