version: "2.0"

services:
  pwndrop:
    image: linuxserver/pwndrop
    expose:
      - port: 8080
        as: 8080
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=5ad39c35364efdb83ec2523d95cee97d
      - SECRET_PATH=/pwndrop
      - TZ=Etc/UTC

profiles:
  compute:
    pwndrop:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        pwndrop:
          denom: uakt
          amount: 100000
deployment:
  pwndrop:
    akash:
      profile: pwndrop
      count: 1
