version: "2.0"

services:
  letsencrypt:
    image: linuxserver/letsencrypt
    expose:

    env:

profiles:
  compute:
    letsencrypt:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        letsencrypt:
          denom: uakt
          amount: 100000
deployment:
  letsencrypt:
    akash:
      profile: letsencrypt
      count: 1
