version: "2.0"

services:
  telegraf:
    image: telegraf
    expose:

    env:

profiles:
  compute:
    telegraf:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 8Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        telegraf:
          denom: uakt
          amount: 100000
deployment:
  telegraf:
    akash:
      profile: telegraf
      count: 1
