version: "2.0"

services:
  mstream:
    image: linuxserver/mstream
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=1f1729d7cbb41731f86e4d6e64ab591d
      - TZ=Etc/UTC

profiles:
  compute:
    mstream:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        mstream:
          denom: uakt
          amount: 100000
deployment:
  mstream:
    akash:
      profile: mstream
      count: 1
