version: "2.0"

services:
  remmina:
    image: linuxserver/remmina
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 3001
        as: 3001
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=a971380298ca3953abb32deefd48ffc9
      - TZ=Etc/UTC

profiles:
  compute:
    remmina:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        remmina:
          denom: uakt
          amount: 100000
deployment:
  remmina:
    akash:
      profile: remmina
      count: 1
