version: "2.0"

services:
  apprise-api:
    image: linuxserver/apprise-api
    expose:
      - port: 8000
        as: 8000
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=f04f1b50cf45e0fbaf20731b332f8717
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC

profiles:
  compute:
    apprise-api:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        apprise-api:
          denom: uakt
          amount: 100000
deployment:
  apprise-api:
    akash:
      profile: apprise-api
      count: 1
