version: "2.0"

services:
  quassel-web:
    image: linuxserver/quassel-web
    expose:
      - port: 64443
        as: 64443
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=f9c86201ef2da73f0ee931072cf233c5
      - PGID=1000
      - PUID=1000
      - QUASSEL_CORE=192.168.1.10
      - QUASSEL_PORT=4242
      - TZ=Etc/UTC
      - URL_BASE=/quassel

profiles:
  compute:
    quassel-web:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        quassel-web:
          denom: uakt
          amount: 100000
deployment:
  quassel-web:
    akash:
      profile: quassel-web
      count: 1
