version: "2.0"

services:
  cloud9:
    image: linuxserver/cloud9
    expose:
      - port: 8000
        as: 8000
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=94e8e8efa3c2757411713393a91a2fea
      - GITURL=https://github.com/linuxserver/docker-cloud9.git
      - PASSWORD=
      - TZ=Europe/London
      - USERNAME=

profiles:
  compute:
    cloud9:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        cloud9:
          denom: uakt
          amount: 100000
deployment:
  cloud9:
    akash:
      profile: cloud9
      count: 1
