version: "2.0"

services:
  orbitty-tx2-alpine-python:
    image: balenalib/orbitty-tx2-alpine-python
    expose:

    env:

profiles:
  compute:
    orbitty-tx2-alpine-python:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 8Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        orbitty-tx2-alpine-python:
          denom: uakt
          amount: 100000
deployment:
  orbitty-tx2-alpine-python:
    akash:
      profile: orbitty-tx2-alpine-python
      count: 1
