version: "2.0"

services:
  webcord:
    image: linuxserver/webcord
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 3001
        as: 3001
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=c74a54d020c0b2c5c9d9138aaadf21c1
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC

profiles:
  compute:
    webcord:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        webcord:
          denom: uakt
          amount: 100000
deployment:
  webcord:
    akash:
      profile: webcord
      count: 1
