version: "2.0"

services:
  medusa:
    image: linuxserver/medusa
    expose:
      - port: 8081
        as: 8081
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=f6e9a280a1573f56c864bedbc1a33f19
      - TZ=Etc/UTC

profiles:
  compute:
    medusa:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        medusa:
          denom: uakt
          amount: 100000
deployment:
  medusa:
    akash:
      profile: medusa
      count: 1
