version: "2.0"

services:
  plexpy:
    image: linuxserver/plexpy
    expose:
      - port: 8181
        as: 8181
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - TZ=TZ
      - TZ=<timezone>

profiles:
  compute:
    plexpy:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        plexpy:
          denom: uakt
          amount: 100000
deployment:
  plexpy:
    akash:
      profile: plexpy
      count: 1
