version: "2.0"

services:
  taisun:
    image: linuxserver/taisun
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=9aebc2401e8bef27b631650a5dd00427

profiles:
  compute:
    taisun:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        taisun:
          denom: uakt
          amount: 100000
deployment:
  taisun:
    akash:
      profile: taisun
      count: 1
