version: "2.0"

services:
  oscam:
    image: linuxserver/oscam
    expose:
      - port: 8888
        as: 8888
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=a0ec21616a372fa61ca6114cf4ad710b
      - TZ=Etc/UTC

profiles:
  compute:
    oscam:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        oscam:
          denom: uakt
          amount: 100000
deployment:
  oscam:
    akash:
      profile: oscam
      count: 1
