version: "2.0"

services:
  snapdrop:
    image: linuxserver/snapdrop
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 443
        as: 443
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=0f1c62fcc993eae3e54221605ae4ffcc
      - TZ=Etc/UTC

profiles:
  compute:
    snapdrop:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        snapdrop:
          denom: uakt
          amount: 100000
deployment:
  snapdrop:
    akash:
      profile: snapdrop
      count: 1
