version: "2.0"

services:
  cardigann:
    image: linuxserver/cardigann
    expose:
      - port: 5060
        as: 5060
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true

    env:
      - PASSWORD=889de9481dc415d81157c84b89673c89
      - HTTP_PROXY=IP:PORT
      - SOCKS_PROXY=IP:PORT
      - SOCKS_PROXY=localhost:1080

profiles:
  compute:
    cardigann:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 2.5Gi
        storage:
          size: 32Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        cardigann:
          denom: uakt
          amount: 100000
deployment:
  cardigann:
    akash:
      profile: cardigann
      count: 1
